FROM rust:slim AS builder

WORKDIR /usr/src
COPY . /usr/src

RUN --mount=type=cache,target=/volume/target \
  --mount=type=cache,target=/root/.cargo/registry \
  cargo build --release

FROM debian:stable-slim
LABEL org.opencontainers.image.authors="rigma"

COPY --from=builder /usr/src/target/release/backbone-metadata /app/backbone-metadata

EXPOSE 80

CMD [ "/app/backbone-metadata", "--host", "0.0.0.0", "--port", "80" ]
