[package]
name = "metadata-http"
version.workspace = true
edition.workspace = true

[lib]
name = "metadata_http"

[dependencies]
axum.workspace = true
metadata-data-layer = { path = "../metadata-data-layer" }
metadata-data-layer-utils = { path = "../metadata-data-layer-utils" }
