[package]
name = "metadata-http-utils"
version.workspace = true
edition.workspace = true

[lib]
name = "metadata_http_utils"

[dependencies]
axum.workspace = true
http = "^1.1.0"
serde_json = "*"
sqlx.workspace = true
